// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(PortfoliodbContext))]
    [Migration("20241116172532_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Portfolio.Models.Education", b =>
                {
                    b.Property<int>("Education_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kejuruan")
                        .HasColumnType("TEXT")
                        .HasColumnName("Instansi Pendidikan");

                    b.Property<string>("Lembaga")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Lulus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Mulai")
                        .HasColumnType("TEXT");

                    b.Property<int>("Profile_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tingkat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tingkat Pendidikan");

                    b.HasKey("Education_Id");

                    b.HasIndex("Profile_Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("Portfolio.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domisili")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal_Lahir")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tanggal Lahir");

                    b.Property<byte[]>("dataByte")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Portfolio.Models.Project", b =>
                {
                    b.Property<int>("Project_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama_Project")
                        .HasColumnType("TEXT")
                        .HasColumnName("Nama Project");

                    b.Property<int>("Profile_Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Waktu_Mulai")
                        .HasColumnType("TEXT")
                        .HasColumnName("Waktu Mulai");

                    b.Property<DateTime?>("Waktu_Selesai")
                        .HasColumnType("TEXT")
                        .HasColumnName("Waktu Selesai");

                    b.HasKey("Project_Id");

                    b.HasIndex("Profile_Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Portfolio.Models.Education", b =>
                {
                    b.HasOne("Portfolio.Models.Profile", "Profile")
                        .WithMany("Educations")
                        .HasForeignKey("Profile_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Models.Project", b =>
                {
                    b.HasOne("Portfolio.Models.Profile", "Profile")
                        .WithMany("Projects")
                        .HasForeignKey("Profile_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Models.Profile", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
